//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 Area 的本地化字符串。
        /// </summary>
        internal static string ButtonArea {
            get {
                return ResourceManager.GetString("ButtonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Black background 的本地化字符串。
        /// </summary>
        internal static string ButtonBackGround {
            get {
                return ResourceManager.GetString("ButtonBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Distance 的本地化字符串。
        /// </summary>
        internal static string ButtonDistance {
            get {
                return ResourceManager.GetString("ButtonDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Fit to window 的本地化字符串。
        /// </summary>
        internal static string ButtonFitToWindow {
            get {
                return ResourceManager.GetString("ButtonFitToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Download CSV 的本地化字符串。
        /// </summary>
        internal static string ButtonGetCSV {
            get {
                return ResourceManager.GetString("ButtonGetCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string ButtonInfo {
            get {
                return ResourceManager.GetString("ButtonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Layers 的本地化字符串。
        /// </summary>
        internal static string ButtonLayers {
            get {
                return ResourceManager.GetString("ButtonLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Load from HDD 的本地化字符串。
        /// </summary>
        internal static string ButtonLoadFromHDD {
            get {
                return ResourceManager.GetString("ButtonLoadFromHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Load from Web 的本地化字符串。
        /// </summary>
        internal static string ButtonLoadFromWeb {
            get {
                return ResourceManager.GetString("ButtonLoadFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Orbit 的本地化字符串。
        /// </summary>
        internal static string ButtonOrbit {
            get {
                return ResourceManager.GetString("ButtonOrbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Polyline 的本地化字符串。
        /// </summary>
        internal static string ButtonPolyline {
            get {
                return ResourceManager.GetString("ButtonPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Zoom in 的本地化字符串。
        /// </summary>
        internal static string ButtonZoomIn {
            get {
                return ResourceManager.GetString("ButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Zoom out 的本地化字符串。
        /// </summary>
        internal static string ButtonZoomOut {
            get {
                return ResourceManager.GetString("ButtonZoomOut", resourceCulture);
            }
        }
    }
}
